services:
  oracle:
    image: 'gvenzl/oracle-xe:latest'
    environment:
      - 'ORACLE_PASSWORD=secret'
    ports:
      - '1521'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
